<a href="https://colab.research.google.com/github/lpoggetto/fiap_reinforcement_learning/blob/main/aula1_script.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# instalar bibilioteca do OpenAI Gym

!pip install gym
!pip install numpy

In [ ]:
# importanto pacotes que serao utilizados
import gym
import numpy as np
import random
from IPython.display import clear_output, display
from time import sleep

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
env = gym.make('Taxi-v3')

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [ ]:
# Criando uma nova instancia do Taxi, e aferir o estado inicial

state = env.reset() # Boas praticas de reset de ambiente

print(f'Initiali State: {state}')

Initiali State: 442


In [ ]:
# Comportamento aleatorio

num_steps = 99 # numero de passos do algoritmo

for s in range(num_steps+1):

  clear_output(wait=True)

  print(f'step: {s} of {num_steps}')

  action = env.action_space.sample()

  env.step(action)

  sleep(0.2)

env.close()

step: 99 of 99


In [ ]:
# Q-Table implementation

state_size = env.observation_space.n
action_size = env.action_space.n

q_table = np.zeros((state_size, action_size))

print(f'Q-Table: {qtable}')

Q-Table: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
from types import new_class
# Algoritmo Q-Learning

learning_rate = 0.9
discount_rate = 0.8

reward = 10 # R_(t+1)
state = env.observation_space.sample() #S_t
action = env.action_space.sample() #A_t
new_state = env.observation_space.sample() #S_(t+1)

# implementacao da funcao q-learning

q_table[state, action] = q_table[state, action] + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]) - q_table[state, action])

print(f'Q-valor para (state,action), par ({state}, {action}: {q_table[state,action]})')

Q-valor para (state,action), par (352, 2: 9.0)


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
# Exploration vs Exploitation

# dummy variables
episode = random.randint(0,500)
q_table = np.random.randn(env.observation_space.sample(), env.action_space.sample())

# hyperparameters
epsilon = 1.0 # probabilidade explorar
decay_rate = 0.01 # of epsilon

if random.uniform(0,1) < epsilon:
  # Exploration
  action = env.action_space.sample()
else:
  # Exploitation
  action = np.argmax(q_table[state,:])

epsilon = np.exp(-decay_rate*episode)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
